package website.sung.mangossh.session

import androidx.test.platform.app.InstrumentationRegistry
import java.security.MessageDigest
import java.util.Base64
import kotlinx.coroutines.*
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Assume.assumeTrue
import org.junit.Test
import website.sung.mangossh.data.keys.SshKeyManager
import website.sung.mangossh.session.ssh.*

/** Keys and answers are generated by OpenSSH inside the disposable Linux fixture, never checked in. */
class SshMigrationInstrumentedTest {
    private fun port(name: String = "fixturePort"): Int {
        val args = InstrumentationRegistry.getArguments()
        val value = args.getString(name)?.toIntOrNull()
        if (args.getString("requireFixtures") == "true") assertNotNull(value)
        assumeTrue(value != null)
        return value!!
    }
    private suspend fun connect(port: Int): SshConnection = SshConnection("127.0.0.1", port).also {
        it.connect(10_000) { _, _ -> true }
    }
    private suspend fun text(connection: SshConnection, path: String): String =
        requireNotNull(RemoteFileClient().readTextPreview(connection, path, 64 * 1024)).text
    private suspend fun metadata(connection: SshConnection): JSONObject = connection.openChannel().use { channel ->
        channel.execute("fixture-auth")
        val data = withContext(Dispatchers.IO) { BoundedProtocolReader.bytes(channel.stdout, 64 * 1024) }
        assertEquals(0, withTimeout(5_000) { channel.exitCode() })
        JSONObject(data.toString(Charsets.UTF_8))
    }

    @Test fun opensshAndPemKeysKeepPublicIdentityAndEncryptedBytes() = runBlocking<Unit> {
        val port = port()
        val source = connect(port)
        try {
            assertTrue(source.authenticate("fixture", object : SshCredentials {}))
            val entries = metadata(source).getJSONArray("entries")
            assertEquals(9, entries.length())
            val manager = SshKeyManager()
            for (index in 0 until entries.length()) {
                val entry = entries.getJSONObject(index)
                val expected = entry.getString("public").split(' ')
                val expectedBlob = Base64.getDecoder().decode(expected[1])
                val fingerprint = "SHA256:" + Base64.getEncoder().withoutPadding().encodeToString(
                    MessageDigest.getInstance("SHA-256").digest(expectedBlob))
                for (encrypted in listOf(false, true)) {
                    val pem = text(source, entry.getString(if (encrypted) "encrypted" else "plain"))
                    val passphrase = if (encrypted) entry.getString("passphrase") else null
                    val record = manager.importPrivateKey("fixture", pem, passphrase)
                    assertTrue("Public key identity changed", record.publicKey.split(' ').take(2) == expected)
                    assertTrue("Fingerprint changed", record.fingerprint == fingerprint)
                    assertTrue("Stored private key bytes changed", record.privateKeyPem == pem)
                    assertEquals(encrypted, record.requiresPassphrase)
                    if (encrypted) {
                        assertThrows(Exception::class.java) { manager.decodeKeyPair(record, java.util.UUID.randomUUID().toString()) }
                    }
                    val connection = connect(port)
                    try {
                        assertTrue("Public-key authentication failed", connection.authenticate("fixture-key", object : SshCredentials {
                            override suspend fun key() = manager.decodeKeyPair(record, passphrase)
                        }))
                    } finally { connection.close() }
                }
            }
            source.keepalive()
        } finally { source.close() }
    }

    @Test fun passwordOtpAndAuthenticationCancellationRemainIsolated() = runBlocking<Unit> {
        val port = port()
        val source = connect(port)
        try {
            assertTrue(source.authenticate("fixture", object : SshCredentials {}))
            val answers = metadata(source)
            for (otp in listOf(false, true)) {
                val connection = connect(port)
                try {
                    assertTrue(connection.authenticate(if (otp) "fixture-otp" else "fixture-password", object : SshCredentials {
                        override suspend fun password() = if (otp) null else answers.getString("password")
                        override suspend fun interactive(name: String, instruction: String, fields: List<SshPromptField>): List<String>? {
                            if (!otp) return null
                            assertEquals(1, fields.size)
                            assertFalse(fields.single().echo)
                            return listOf(answers.getString("otp"))
                        }
                    }))
                } finally { connection.close() }
            }
            val cancelled = connect(port)
            try {
                assertSuspendingThrows(CancellationException::class.java) {
                    cancelled.authenticate("fixture-otp", object : SshCredentials {
                        override suspend fun interactive(name: String, instruction: String, fields: List<SshPromptField>): List<String>? =
                            throw CancellationException("Fixture prompt cancelled")
                    })
                }
                assertSuspendingThrows(SshFailure::class.java) { cancelled.openChannel() }
            } finally { cancelled.close() }
            source.keepalive()
        } finally { source.close() }
    }

    @Test fun changedHostKeyIsRejectedAndNormalExitDrainsBothStreams() = runBlocking<Unit> {
        var trusted: ByteArray? = null
        val first = SshConnection("127.0.0.1", port())
        try {
            first.connect(10_000) { _, blob -> trusted = blob.copyOf(); true }
            assertTrue(first.authenticate("fixture", object : SshCredentials {}))
            first.openChannel().use { channel ->
                first.enableAgent(object : SshAgent {
                    override fun identities() = emptyList<SshAgentIdentity>()
                    override fun keyForSignature(publicKey: ByteArray): java.security.KeyPair? = null
                })
                assertFalse(channel.requestAgentForwarding())
                channel.pty("xterm-256color", 80, 24)
                channel.resize(100, 36)
                channel.execute("fixture-output")
                val stdout = async(Dispatchers.IO) { channel.stdout.readBytes().size }
                val stderr = async(Dispatchers.IO) { channel.stderr.readBytes().size }
                withTimeout(15_000) {
                    assertEquals(512 * 1024, stdout.await())
                    assertEquals(256 * 1024, stderr.await())
                    assertEquals(0, channel.exitCode())
                }
            }
            first.keepalive()
            val changed = SshConnection("127.0.0.1", port("fixtureFallbackPort"))
            try {
                val failure = assertSuspendingThrows(SshFailure::class.java) {
                    changed.connect(10_000) { _, blob -> blob.contentEquals(requireNotNull(trusted)) }
                }
                assertEquals(SshFailure.Category.HOST_KEY, failure.category)
            } finally { changed.close() }
        } finally { first.close() }
    }
}
